networks:
  coredns:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16

services:
  coredns-master:
    build:
      context: ../..
      dockerfile: Dockerfile
    container_name: coredns-master
    networks:
      coredns:
        ipv4_address: 172.100.0.100
    ports:
      - "5300:53/udp"
    volumes:
      - ./Corefile.master:/Corefile:ro
      - ./hosts:/etc/hosts:ro

  peer1:
    image: coredns/coredns:latest
    container_name: peer1
    networks:
      coredns:
        ipv4_address: 172.100.0.101
    volumes:
      - ./Corefile.peers:/Corefile:ro # Mount Corefile for configuration

  peer2:
    image: coredns/coredns:latest
    container_name: peer2
    networks:
      coredns:
        ipv4_address: 172.100.0.102
    volumes:
      - ./Corefile.peers:/Corefile:ro # Mount Corefile for configuration

  peer3:
    image: coredns/coredns:latest
    container_name: peer3
    networks:
      coredns:
        ipv4_address: 172.100.0.103
    volumes:
      - ./Corefile.peers:/Corefile:ro # Mount Corefile for configuration
